### ISSUE TITLE
[bug] mysql 8 error

### ISSUE THREAD

**Issue by XQDD** [xelabs/go-mydumper#17]
```Prolog
ubuntu1804@XQDD-PC:~/go-mydumper/bin$ ./myloader -h localhost -P 3306 -u XQDD -p 1234-d test.sql
panic: pkt.read.seq[3]!=pkt.actual.seq[1] (errno 1835) (sqlstate HY000)

goroutine 1 [running]:
common.AssertNil(0x583160, 0xc420022540)
        /home/ubuntu1804/go-mydumper/src/common/common.go:75 +0x4a
common.restoreDatabaseSchema(0xc420098430, 0xc42005a340, 0x1, 0x1, 0xc4200a23a0)
        /home/ubuntu1804/go-mydumper/src/common/loader.go:75 +0x84
common.Loader(0xc420098430, 0xc420069e80)
        /home/ubuntu1804/go-mydumper/src/common/loader.go:161 +0x18a
main.main()
        /home/ubuntu1804/go-mydumper/src/myloader/main.go:62 +0x1e7
```

**Comment by BohuTANG** [comment]
@XQDD 

We have not any tests on MySQL 8.0.
From the panic stack, looks like a protocol issue.
Thanks for your report.
