### ISSUE TITLE
Doesn't work with mysql version8

### ISSUE THREAD

**Issue by NishanthSpShetty** [xelabs/go-mydumper#37]
hello,

I was testing this program with by running MySQL on a docker, tried version 8.0 and above and got the following the error.

```
sec=where keys=[]
panic: pkt.read.seq[3]!=pkt.actual.seq[1] (errno 1835) (sqlstate HY000)

goroutine 1 [running]:
github.com/xelabs/go-mydumper/common.AssertNil(...)
        /Users/system-user/projects/repos/go-mydumper/common/common.go:50
github.com/xelabs/go-mydumper/common.dumpDatabaseSchema(0xc000060760, 0xc0001a0040, 0xc0001263c0, 0xc000018499, 0x4)
        /Users/system-user/projects/repos/go-mydumper/common/dumper.go:32 +0x2db
github.com/xelabs/go-mydumper/common.Dumper(0xc000060760, 0xc0001263c0)
        /Users/system-user/projects/repos/go-mydumper/common/dumper.go:214 +0x268
main.main()
        /Users/system-user/projects/repos/go-mydumper/cmd/mydumper/main.go:56 +0x169

```

When I tried using version 5.0, I was able to get rid of this error. I believe MySQL-client version may need to be updated.

**Comment by bohutang** [comment]
There is no plan to support 8.0 yet, welcome to improve.

**Comment by NishanthSpShetty** [comment]
I believe to support this we would have to make changes in SQL client used here, which is [go-mysqlstack](https://github.com/xelabs/go-mysqlstack)
